version: "3.9"
services:
    
  app:
    container_name: books-service
    build: .
    depends_on:
      - postgres
    ports:
      - 3000:3000
    restart: always
    environment:
      #jwt
      - SECRET_KEY=$SECRET_KEY
      #mailer
      - SMTP_HOST=$SMTP_HOST
      - SMTP_PORT=$SMTP_PORT
      - SMTP_USER=$SMTP_USER
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - SMTP_FROM=$SMTP_FROM
      #localhost
      - HOST=$HOST
      #DB
      - DB_HOST=postgres
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_PASSWORD
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true
    networks:
      - pg-express
    expose:
      - 3000

  postgres:
    container_name: books-service-pg
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD?"Не задана переменная окружения DB_PASSWORD"}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg-express
    expose:
      - 5432
    ports:
      - 5433:5432

networks:
  pg-express:

volumes:
  postgres_data:
      